package io.customer.remotehabits

/**
 * Object containing variables that change the runtime execution of the app depending on the environment. Like a `.env` file.
 *
 * The plan is that this file is automatically generated in the future. This is a placeholder.
 */
object Env {

    val appName = "Remote Habits"
    val isDevelopment = true
    val pokeApiEndpoint = "https://pokeapi.co/api/v2/"

}