# There are some re-usable functions in other Fastfile files in the org we can re-use. 
import_from_git(
  url: "https://github.com/customerio/customerio-ios.git", 
  branch: "levi/fastlane-github-reusable", 
  path: "Apps/fastlane/Fastfile"
)

platform :android do 
  lane :build do |values|    
    new_app_version = get_new_app_version()
    new_build_number = Time.now.to_i.to_s # Build numbers need to be unique, only 0-9 digits, and always incremented. Using seconds now solves both of those problems easily. 
    build_notes = get_build_notes()
    test_groups = get_build_test_groups()  
    app_package_name = CredentialsManager::AppfileConfig.try_fetch_value(:package_name) # get package_name from Appfile

    UI.important(find_firebase_app_id(app_identifier: app_package_name))

    # Modify the source code with the new app version and build number before we compile the iOS app. This is a good idea to do to make installing builds on a test device easier. 
    # The iOS OS might give errors when trying to install a build of an app if the app is already installed on the device. Having unique build number or app version can avoid those errors. 
    android_set_version_name(version_name: new_app_version)
    android_set_version_code(version_code: new_build_number)

    build_android_app(
      task: 'assemble',
      build_type: 'Release'
    )

    # function 'setup_google_bucket_access' is a re-usable function inside of apple-code-signing Fastfile that we imported. 
    # This allows you to create a temporary file from a GitHub secret for added convenience. 
    # When uploading the build to Firebase App Distribution, the CI server needs to authenticate with Firebase. This is done with a 
    # Google Cloud Service Account json creds file. The base64 encoded value of this service account file is stored as this secret.  
    service_credentials_file_path = setup_google_bucket_access(
      environment_variable_key: "FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_CREDS_B64"
    )

    firebase_app_distribution(
      app: find_firebase_app_id(app_identifier: app_package_name), # Firebase app id is required. Get it from google-services.json file
      service_credentials_file: service_credentials_file_path,
      groups: test_groups,
      release_notes: build_notes
    )
  end 
end 