name: Tests

on: [pull_request]

jobs:
  deploy-builds:
    runs-on: ubuntu-latest
    name: Deploy development builds
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11' # Robolectric requires v9, but we choose LTS: https://adoptopenjdk.net/
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Prepare app for building
        run: echo "${{ secrets.GOOGLE_SERVICES_BASE64 }}" | base64 -d > app/google-services.json
        env:
          GOOGLE_SERVICES_BASE64: "${{ secrets.GOOGLE_SERVICES_BASE64 }}"
      - name: Prepare app for building
        run: echo "${{ secrets.GOOGLE_SERVICES_BASE64 }}" | base64 -d > app/google-services.json
        env:
          GOOGLE_SERVICES_BASE64: "${{ secrets.GOOGLE_SERVICES_BASE64 }}"
      - name: Create Local Properties File
        run: touch local.properties
      - name: Add CIO creds secret in local properties
        run: |
          echo "siteId=${{ secrets.CIO_SITE_ID }}" >> local.properties
          echo "apiKey=${{ secrets.CIO_API_KEY }}" >> local.properties
          echo "orgId=${{ secrets.GIST_ORG_ID }}" >> local.properties
      - name: Setup Ruby to run Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Setup for Firebase App Distribution
        id: setup
        run: |
          echo "${{ secrets.FIREBASE_APP_DISTRIBUTION_GOOGLE_AUTH }}" | base64 -d > firebase_appdistribution_service_account.json
          echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 -d > upload.keystore
        env:
          FIREBASE_APP_DISTRIBUTION_GOOGLE_AUTH: ${{ secrets.FIREBASE_APP_DISTRIBUTION_GOOGLE_AUTH }}
          RELEASE_KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}

      - name: Deploy development build via Fastlane
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'deploy_app'
          skip-tracking: true
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          ANDROID_SIGNING_ALIAS: ${{ secrets.ANDROID_SIGNING_ALIAS }}
          ANDROID_SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
          ANDROID_SIGNING_STORE_PASSWORD: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}
