name: Tests

on: [pull_request]

jobs:
  deploy-builds:
    runs-on: ubuntu-latest
    name: Deploy development builds
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Create Local Properties File
        run: touch local.properties

      - name: Add CIO creds secret in local properties
        run: |
          echo "siteId=${{ secrets.CIO_SITE_ID }}" >> local.properties
          echo "apiKey=${{ secrets.CIO_API_KEY }}" >> local.properties
          echo "orgId=${{ secrets.GIST_ORG_ID }}" >> local.properties

      - name: Setup Ruby to run Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Setup for Firebase App Distribution
        run: echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 -d > upload.keystore

      - name: Deploy development build via Fastlane
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'android build'
        env:
          ANDROID_SIGNING_ALIAS: ${{ secrets.ANDROID_SIGNING_ALIAS }}
          ANDROID_SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
          ANDROID_SIGNING_STORE_PASSWORD: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}
          FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_CREDS_B64: ${{ secrets.FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_CREDS_B64 }}