name: Tests
on: [push, pull_request]

jobs:
  jvm-test:
    runs-on: ubuntu-latest
    name: TEST DUMP
    # skip if '[skip ci]' exists in commit message 
    if: ${{ !contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[skip ci]') }}
    steps:
    - uses: actions/checkout@v2
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: 
        echo "$GITHUB_CONTEXT"
        echo "$GITHUB_CONTEXT" > github_context.json
    - name: see file contents 
      run: cat github_context.json        
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJSON(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJSON(steps) }}
      run: echo "$STEPS_CONTEXT"