name: Tests
on: [push, pull_request]

jobs:
  jvm-test:
    runs-on: ubuntu-latest
    name: JVM tests
    # skip if '[skip ci]' exists in commit message 
    if: ${{ !contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[skip ci]') }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11' # Robolectric requires v9, but we choose LTS: https://adoptopenjdk.net/
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Run unit tests
      run: ./gradlew :app:testDebugUnitTest

    - name: Publish test results
      uses: mikepenz/action-junit-report@v2      
      with:
        report_paths: 'app/build/test-results/test*/TEST-*.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_failure: true 
        require_tests: true 
      if: ${{ always() }} # if running tests fails, we still want to parse the test results 